### ISSUE TITLE
add a klaw emoji

### ISSUE THREAD

**Issue by nzewail** [benmayne/slack-emojis#3]
if Kawhi Leonard signs with the lakers we need a Klaw emoji to this pack

**Comment by ewalker41** [comment]
Following!

**Comment by benmayne** [comment]
What's a klaw?

**Comment by nzewail** [comment]
![image](https://user-images.githubusercontent.com/29211170/60305961-501c0800-98f3-11e9-9a15-c47b0dd780c5.png)

**Comment by bcoppersmith** [comment]
lol he's not coming to the lakers

**Comment by nzewail** [comment]
dont be a hater. also why are you following this pretty random repo

**Comment by ewalker41** [comment]
Because it's more entertaining than the Phoenix Suns!

**Comment by bcoppersmith** [comment]
hey you better watch out, we're one overpaid terry rozier from being 10th in the west!!
